#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-PageBuilder
version:      0.8
version_from: PageBuilder.pm
installdirs:  site
requires:
    CGI::Application:              4.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
