---
name: CGI-Application-Plugin-PageBuilder
version: 0.97
author:
  - 'Clint Moore E<lt>cmoore@cpan.orgE<gt>'
abstract: Simplifies building pages with multiple templates.
license: perl
requires:
  CGI::Application: 4
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  CGI::Application::Plugin::PageBuilder:
    file: lib/CGI/Application/Plugin/PageBuilder.pm
    version: 0.97
resources:
  license: http://dev.perl.org/licenses/
