--- #YAML:1.0
name:                CGI-Application-Plugin-PageBuilder
version:             0.96
abstract:            Simplifies building pages with multiple templates.
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_03
author:              Clint Moore <cmoore@cpan.org>
distribution_type:   module
requires:     
    CGI::Application:              4.0
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
